# Generated by Django 5.1.7 on 2025-03-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_message_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="message",
            new_name="room",
        ),
    ]
