# Generated by Django 5.1.7 on 2025-03-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_rename_message_message_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="chat_files/"),
        ),
    ]
